#!/usr/bin/env python3
"""Combine multiple PDFs into one file."""
import argparse
from pathlib import Path

from pypdf import PdfReader, PdfWriter


def main():
    parser = argparse.ArgumentParser()
    parser.add_argument("files", nargs="*", help="PDFs to concatenate.")
    parser.add_argument("-o", "--outfile", help="Name of combined PDF output.")
    args = parser.parse_args()

    writer = PdfWriter()

    # add all pages to the writer and rotate them
    for f in args.files:
        reader = PdfReader(f)
        for i in range(len(reader.pages)):
            writer.add_page(reader.pages[i])

    if args.outfile is None:
        outfile = "combined.pdf"
    else:
        outfile = args.outfile

    with open(outfile, "wb") as fp:
        writer.write(fp)
    print(f"Saved pruned PDF to {outfile}.")


main()
