#!/usr/bin/env python3
"""Rotate the pages of a PDF."""
import argparse
from pathlib import Path

from pypdf import PdfReader, PdfWriter


def main():
    parser = argparse.ArgumentParser()
    parser.add_argument("infile", help="PDF to rotate")
    parser.add_argument("-o", "--outfile", help="Name of rotated PDF output")
    parser.add_argument(
        "--angle", type=int, default=90, help="Angle to rotate, in degrees."
    )
    args = parser.parse_args()

    reader = PdfReader(args.infile)
    writer = PdfWriter()

    # add all pages to the writer and rotate them
    for i in range(len(reader.pages)):
        writer.add_page(reader.pages[i])
        writer.pages[i].rotate(args.angle)

    if args.outfile is None:
        outfile = str(Path(args.infile).stem) + "_rotated.pdf"
    else:
        outfile = args.outfile

    with open(outfile, "wb") as fp:
        writer.write(fp)
    print(f"Saved rotated PDF to {outfile}.")


main()
